apiVersion: v1
kind: Service
metadata:
  name: homepage-test-database
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: homepage-test-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Pod
metadata:
  name: homepage-test-database
  labels:
    app.kubernetes.io/name: homepage-test-database
spec:
  containers:
    - name: mongodb
      image: mongo:4.4.6
      ports:
        - name: web
          containerPort: 27017
          protocol: TCP
