:toc: right
:backend: html5
:doctitle: Homepage
:doctype: book
:icons: font
:!numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:toclevels: 2

= Homepage
All source files for my private homepage

== *Version*
=== 1.14.0 - 14/09/2016

==== NEW
    ---------------------
    updated CV
    - added Diebold Nixdorf


=== 1.12.0 - 11/03/2016

==== NEW
    ---------------------
    http-status "not found" causes a redirect
    - if an invalid url is executed the user is redirected to the main page


==== CHANGE
    ---------------------
    finalizing new readme
    - including cukedoctor into the final readme-file
    
    ---------------------
    changing format from md to adoc
    - preparing to use cukedoctor for cucumber report
    
    ---------------------
    added cucumber testcases for 404
    - testing unknown links
    
    ---------------------
    using cucumber for e2e tests
    - e2e tests changed to work with cucumber and features
    
    ---------------------
    changes.xml not needed anymore
    - changelog is handled via the commit messages
    
    ---------------------
    restructured
    - moving all source files to src


==== FIX
    ---------------------
    redirecting 404 back to main entry
    - adding own 404.html which redirects to /
    
    ---------------------
    corrected bower folder
    - need to ignore a certain string
    - basePath is used to find components
    
    ---------------------
    resetting mail form
    - form was not resetted when the "x" button was pressed


=== 1.12.0 - 23/02/2016

==== NEW
    ---------------------
    added robots.txt
    - for allowing search engines to check my homepage
    - currently i don't have anything to hide
    
    ---------------------
    pdf profile
    - added link to download
    
    ---------------------
    added files to create a pdf profile
    - using asciidoctor-pdf to create pdf


==== CHANGE
    ---------------------
    new pdf profile layout
    - adding different table style
    - completed skill list
    
    ---------------------
    removing profile from version
    - the new version name contains the profile now
    
    ---------------------
    creating new build process with jenkins
    - using nexus for all artifacts
    
    ---------------------
    moving conf-files to elk repository
    - don't provide conf-file per build
    
    ---------------------
    added background
    - previously the image had a transparent layer
    - added a grey background for pdf profile
    
    ---------------------
    remove unneeded image
    - only using own background image


=== 1.11.0 - 08/02/2016

==== CHANGE
    ---------------------
    updated elk stack
    - using json output for elk
    
    ---------------------
    using json as logging output
    - with json it should be easier to use ELK


=== 1.10.0 - 02/02/2016

==== CHANGE
    ---------------------
    building node modules from maven
    - as all jenkins problems could be solved, the whole build is done via maven
    
    ---------------------
    changed favicon
    - using background image as new favicon
    - previous one was not recognizable


=== 1.9.0 - 01/02/2016

==== NEW
    ---------------------
    speeding up docker build
    - adding .dockerignore to send only important files to docker engine
    
    ---------------------
    add test for back browsing
    - added a test to check if back browsing works
    - previously back navigation refreshed the same page


==== CHANGE
    ---------------------
    updated spring cloud
    - trying to use latest clout starter pom angel.sr6
    - jenkins still makes problems although mvn works on a commandline
    
    ---------------------
    providing more information about my cv
    - added a detailed description of my life so far


==== FIX
    ---------------------
    new: speeding up docker build
    - adding .dockerignore to send only important files to docker engine


=== 1.8.0 - 15/01/2016

==== CHANGE
    ---------------------
    corrected jenkins jobs
    - increased memory on jenkins server
    - aligned mvn directories on master and slave

=== 1.7.0 - 15/01/2016

==== NEW
    ---------------------
    enabled firefox tests
    - e2e tests executed with firefox
    - currently the bootstrap mail modal does not open with protractor
    - but the mail modal works when used manually

=== 1.6.0 - 13/01/2016

==== NEW
    ---------------------
    templates for readme
    - added initial changelog
    - added templates to create final readme file
    
    ---------------------
    commit template
    - start of new changelog file
    - everything is driven via the commit messages


==== CHANGE
    ---------------------
    increase timer for e2e test
    - sometimes selenium test cases fail, after a navigation is made
    - added additional timer to wait before the whole page is loaded


==== FIX
    ---------------------
    back button did not work
    - because of a wrong anchor, any back button refreshed the page
    - added a div with the id 'content' on the home page to fix that
    - adapted test cases


=== 1.5.0 - 06/01/2016

=== 1.4.0 - 06/01/2016

=== 1.3.0 - 25/12/2015

=== 1.2.0 - 09/11/2015

=== 1.1.0 - 31/10/2015

=== 1.0.0 - 18/10/2015

=== 0.4.0 - 13/10/2015

=== 0.3.0 - 26/09/2015

=== 0.2.0 - 24/09/2015

=== 0.1.0 - 11/09/2015

= *Living Documentation*

== *Summary*
[cols="12*^m", options="header,footer"]
|===
3+|Scenarios 7+|Steps 2+|Features: 7

|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status

12+^|*<<Homepage-cv-entry>>*
|0
|17
|17
|0
|16
|44
|0
|0
|2
|62
|13s 327ms
|[red]#*failed*#

12+^|*<<Homepage-disclaimer-entry>>*
|0
|14
|14
|0
|13
|34
|0
|0
|2
|49
|10s 510ms
|[red]#*failed*#

12+^|*<<Homepage-education-entry>>*
|0
|16
|16
|0
|15
|40
|0
|0
|2
|57
|12s 109ms
|[red]#*failed*#

12+^|*<<Homepage-main-entry>>*
|0
|15
|15
|0
|14
|21
|0
|0
|1
|36
|10s 990ms
|[red]#*failed*#

12+^|*<<Homepage-skill-entry>>*
|0
|16
|16
|0
|15
|40
|0
|0
|2
|57
|12s 683ms
|[red]#*failed*#

12+^|*<<Homepage-social-block>>*
|0
|13
|13
|0
|12
|42
|0
|0
|2
|56
|08s 804ms
|[red]#*failed*#

12+^|*<<Homepage-work-entry>>*
|0
|16
|16
|0
|15
|40
|0
|0
|2
|57
|11s 095ms
|[red]#*failed*#
12+^|*Totals*
|0|107|107|0|100|261|0|0|13|374 2+|01m 19s 522ms
|===

== *Features*

[[Homepage-cv-entry, Homepage cv entry]]
=== *Homepage cv entry*

minmax::Homepage-cv-entry[]
****
As a visitor of the Homepage
I should be able to see my cv 
which gives an overview of my life
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "cv" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: CV view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(01s 418ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
CV.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"cvwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: CV view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(738ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
CV.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"cvwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Timeline content icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(765ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Das habe should be visible in the timeline icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Timeline content icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(832ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
That is should be visible in the timeline icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(721ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(772ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(796ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(992ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(769ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(962ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(747ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(756ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(814ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Footer information icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(826ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Amount of experiences icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(707ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
"15" entries must be visible in the timeline icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Back navigation icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(705ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I click on the back button icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Das habe should be visible in the timeline icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

[[Homepage-disclaimer-entry, Homepage disclaimer entry]]
=== *Homepage disclaimer entry*

minmax::Homepage-disclaimer-entry[]
****
As a visitor of the Homepage
I should be able to see my disclaimer 
which gives an overview of the legal stuff
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Disclaimer view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(762ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
DISCLAIMER.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"disclaimerwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Disclaimer view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(955ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
DISCLAIMER.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"disclaimerwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(946ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(765ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(758ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(767ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(714ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(734ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(782ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(817ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(01s 137ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Footer information icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(685ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Amount of paragraphs icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(683ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
"6" entries must be visible in the disclaimer icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

[[Homepage-education-entry, Homepage education entry]]
=== *Homepage education entry*

minmax::Homepage-education-entry[]
****
As a visitor of the Homepage
I should be able to see my education 
which gives an overview of my education
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "education" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Education view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(777ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
EDUCATION.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"educationwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Education view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(856ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
EDUCATION.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"educationwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Basic education elements icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(766ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Ausbildung should be visible in the upper part icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Basic education elements icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(895ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Education should be visible in the upper part icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(746ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(982ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(01s 020ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(704ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(698ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(814ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(669ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(701ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(731ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Footer information icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(714ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Education is listed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(01s 028ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "education" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
FHDW must be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

[[Homepage-main-entry, Homepage main entry]]
=== *Homepage main entry*

minmax::Homepage-main-entry[]
****
As a visitor of the Homepage
I should be able to see a welcome screen 
which gives a first impression
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: First View icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(938ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
the title should equal "Maximilian Wollnik" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
Entwickler should be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: First View icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(715ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
the title should equal "Maximilian Wollnik" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
Developer should be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(875ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(865ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(722ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
Then ::
=====
a link to xing should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(733ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
Then ::
=====
a link to facebook should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(730ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
Then ::
=====
a link to github should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(767ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(963ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
Then ::
=====
a link to google-plus should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(707ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
Then ::
=====
a link to linkedin should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(745ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Footer information icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(791ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
Then ::
=====
a footer must be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Mobile Version icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(711ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
Then ::
=====
the navigation should be changed into a toggle object icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Unknown link icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME,@ignore#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(721ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
When ::
=====
I navigate to "/a/b/c" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
the title should equal "Maximilian Wollnik" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

[[Homepage-skill-entry, Homepage skill entry]]
=== *Homepage skill entry*

minmax::Homepage-skill-entry[]
****
As a visitor of the Homepage
I should be able to see my skills 
which gives a first impression
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "skill" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Work view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(819ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
SKILL.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"skillwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Work view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(699ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
SKILL.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"skillwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Basic skill elements icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(01s 014ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Angular should be visible in the carousel icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Basic skill elements icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(01s 489ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Angular should be visible in the carousel icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(775ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(820ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(743ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(796ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(741ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(704ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(740ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(01s 093ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(793ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Footer information icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(688ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Samples is listed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(761ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "skill" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
10 skills must be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

[[Homepage-social-block, Homepage social block]]
=== *Homepage social block*

minmax::Homepage-social-block[]
****
As a visitor of the Homepage
I should be able to see my socials 
which shows all plattforms
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "home" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Social block icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(949ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I scroll to the bottom icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Schreiben Sie mir eine Mail should be visible in the mail form icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I close the form again icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social block icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(713ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I scroll to the bottom icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Send me a mail should be visible in the mail form icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I close the form again icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Empty form icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(697ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the bottom icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I click on the submit button icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
all form errors are shown icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I close the form again icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Reset form icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(673ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the bottom icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
all form errors are resetted after reopening icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I close the form again icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Wrong email icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(702ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the bottom icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I enter an invalid email address icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
only email error is shown icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I close the form again icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(764ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(704ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(687ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(703ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(753ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(749ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(706ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

[[Homepage-work-entry, Homepage work entry]]
=== *Homepage work entry*

minmax::Homepage-work-entry[]
****
As a visitor of the Homepage
I should be able to see my work 
which gives an impression of some samples
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "work" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Work view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(746ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
WORK.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"workwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Work view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(759ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
WORK.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"workwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Basic work elements icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(01s 009ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Muster should be visible in the upper part icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Basic work elements icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(691ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Samples should be visible in the upper part icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(732ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(684ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(688ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(667ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(705ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(654ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(673ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(687ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(936ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Footer information icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(753ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Samples is listed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(706ms)#

IMPORTANT: JavascriptError: angular is not defined
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at JavascriptError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:180:10)
    at Object.checkLegacyResponse (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/seleni...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
2 samples must be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****


Copyright 2016 Maximilian Wollnik