:toc: right
:backend: html5
:doctitle: Homepage
:doctype: book
:icons: font
:!numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:toclevels: 2

= Homepage
All source files for my private homepage

== *Version*
=== 1.14.0 - 24/05/2018

==== CHANGE
    ---------------------
    disclaimer
    - added new Privacy Policy


=== 1.14.0 - 24/05/2018

==== CHANGE
    ---------------------
    disclaimer
    - added new Privacy Policy
    - disabled gulp tests


=== 1.14.0 - 20/08/2017

==== CHANGE
    ---------------------
    added projects to doc
    - syncing doc with homepage


==== FIX
    ---------------------
    history
    
    ---------------------
    version


=== 1.14.0 - 03/08/2017

==== NEW
    ---------------------
    chg: cv-update
    - adding latest projects
    - removing eureka


==== CHANGE
    ---------------------
    cv-update
    - adding latest projects
    - removing eureka


==== FIX
    ---------------------
    chg: cv-update
    - adding latest projects
    - removing eureka


=== 1.14.0 - 14/09/2016

==== NEW
    ---------------------
    updated CV
    - added Diebold Nixdorf


=== 1.12.0 - 11/03/2016

==== NEW
    ---------------------
    http-status "not found" causes a redirect
    - if an invalid url is executed the user is redirected to the main page


==== CHANGE
    ---------------------
    finalizing new readme
    - including cukedoctor into the final readme-file
    
    ---------------------
    changing format from md to adoc
    - preparing to use cukedoctor for cucumber report
    
    ---------------------
    added cucumber testcases for 404
    - testing unknown links
    
    ---------------------
    using cucumber for e2e tests
    - e2e tests changed to work with cucumber and features
    
    ---------------------
    changes.xml not needed anymore
    - changelog is handled via the commit messages
    
    ---------------------
    restructured
    - moving all source files to src


==== FIX
    ---------------------
    redirecting 404 back to main entry
    - adding own 404.html which redirects to /
    
    ---------------------
    corrected bower folder
    - need to ignore a certain string
    - basePath is used to find components
    
    ---------------------
    resetting mail form
    - form was not resetted when the "x" button was pressed


=== 1.12.0 - 23/02/2016

==== NEW
    ---------------------
    added robots.txt
    - for allowing search engines to check my homepage
    - currently i don't have anything to hide
    
    ---------------------
    pdf profile
    - added link to download
    
    ---------------------
    added files to create a pdf profile
    - using asciidoctor-pdf to create pdf


==== CHANGE
    ---------------------
    new pdf profile layout
    - adding different table style
    - completed skill list
    
    ---------------------
    removing profile from version
    - the new version name contains the profile now
    
    ---------------------
    creating new build process with jenkins
    - using nexus for all artifacts
    
    ---------------------
    moving conf-files to elk repository
    - don't provide conf-file per build
    
    ---------------------
    added background
    - previously the image had a transparent layer
    - added a grey background for pdf profile
    
    ---------------------
    remove unneeded image
    - only using own background image


=== 1.11.0 - 08/02/2016

==== CHANGE
    ---------------------
    updated elk stack
    - using json output for elk
    
    ---------------------
    using json as logging output
    - with json it should be easier to use ELK


=== 1.10.0 - 02/02/2016

==== CHANGE
    ---------------------
    building node modules from maven
    - as all jenkins problems could be solved, the whole build is done via maven
    
    ---------------------
    changed favicon
    - using background image as new favicon
    - previous one was not recognizable


=== 1.9.0 - 01/02/2016

==== NEW
    ---------------------
    speeding up docker build
    - adding .dockerignore to send only important files to docker engine
    
    ---------------------
    add test for back browsing
    - added a test to check if back browsing works
    - previously back navigation refreshed the same page


==== CHANGE
    ---------------------
    updated spring cloud
    - trying to use latest clout starter pom angel.sr6
    - jenkins still makes problems although mvn works on a commandline
    
    ---------------------
    providing more information about my cv
    - added a detailed description of my life so far


==== FIX
    ---------------------
    new: speeding up docker build
    - adding .dockerignore to send only important files to docker engine


=== 1.8.0 - 15/01/2016

==== CHANGE
    ---------------------
    corrected jenkins jobs
    - increased memory on jenkins server
    - aligned mvn directories on master and slave

=== 1.7.0 - 15/01/2016

==== NEW
    ---------------------
    enabled firefox tests
    - e2e tests executed with firefox
    - currently the bootstrap mail modal does not open with protractor
    - but the mail modal works when used manually

=== 1.6.0 - 13/01/2016

==== NEW
    ---------------------
    templates for readme
    - added initial changelog
    - added templates to create final readme file
    
    ---------------------
    commit template
    - start of new changelog file
    - everything is driven via the commit messages


==== CHANGE
    ---------------------
    increase timer for e2e test
    - sometimes selenium test cases fail, after a navigation is made
    - added additional timer to wait before the whole page is loaded


==== FIX
    ---------------------
    back button did not work
    - because of a wrong anchor, any back button refreshed the page
    - added a div with the id 'content' on the home page to fix that
    - adapted test cases


=== 1.5.0 - 06/01/2016

=== 1.4.0 - 06/01/2016

=== 1.3.0 - 25/12/2015

=== 1.2.0 - 09/11/2015

=== 1.1.0 - 31/10/2015

=== 1.0.0 - 18/10/2015

=== 0.4.0 - 13/10/2015

=== 0.3.0 - 26/09/2015

=== 0.2.0 - 24/09/2015

=== 0.1.0 - 11/09/2015

= *Living Documentation*

== *Summary*
[cols="12*^m", options="header,footer"]
|===
3+|Scenarios 7+|Steps 2+|Features: 7

|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status

12+^|*<<Homepage-cv-entry>>*
|8
|8
|16
|33
|8
|19
|0
|0
|2
|62
|01m 31s 795ms
|[red]#*failed*#

12+^|*<<Homepage-disclaimer-entry>>*
|13
|0
|13
|47
|0
|0
|0
|0
|2
|49
|01m 04s 612ms
|[green]#*passed*#

12+^|*<<Homepage-education-entry>>*
|15
|0
|15
|55
|0
|0
|0
|0
|2
|57
|01m 14s 035ms
|[green]#*passed*#

12+^|*<<Homepage-main-entry>>*
|14
|0
|14
|35
|0
|0
|0
|0
|1
|36
|57s 627ms
|[green]#*passed*#

12+^|*<<Homepage-skill-entry>>*
|15
|0
|15
|55
|0
|0
|0
|0
|2
|57
|01m 19s 923ms
|[green]#*passed*#

12+^|*<<Homepage-social-block>>*
|8
|4
|12
|39
|4
|11
|0
|0
|2
|56
|01m 05s 317ms
|[red]#*failed*#

12+^|*<<Homepage-work-entry>>*
|3
|12
|15
|18
|12
|25
|0
|0
|2
|57
|01m 32s 591ms
|[red]#*failed*#
12+^|*Totals*
|76|24|100|282|24|55|0|0|13|374 2+|08m 45s 904ms
|===

== *Features*

[[Homepage-cv-entry, Homepage cv entry]]
=== *Homepage cv entry*

ifndef::backend-pdf[]
minmax::Homepage-cv-entry[]
endif::[]
****
As a visitor of the Homepage
I should be able to see my cv 
which gives an overview of my life
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "cv" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: CV view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 007ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
CV.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"cvwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: CV view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 004ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
CV.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"cvwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Timeline content icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 003ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Das habe should be visible in the timeline icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Timeline content icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
That is should be visible in the timeline icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(04s 999ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 871ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(025ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(010ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 060ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 629ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(011ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 429ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 996ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 275ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 392ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 923ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 210ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(003ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 874ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 616ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(030ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 585ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 145ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 785ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 095ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 148ms)#
=====
****

==== Scenario: Footer information
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 583ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(030ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 774ms)#
=====
****

==== Scenario: Amount of experiences icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 967ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(007ms)#
=====
Then ::
=====
"15" entries must be visible in the timeline icon:thumbs-down[role="red",title="Failed"] [small right]#(03s 086ms)#

IMPORTANT: AssertionError: expected 17 to equal 15
=====
****

==== Scenario: Back navigation icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 175ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
I click on the back button icon:thumbs-up[role="green",title="Passed"] [small right]#(021ms)#
=====
Then ::
=====
Das habe should be visible in the timeline icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 002ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
****

[[Homepage-disclaimer-entry, Homepage disclaimer entry]]
=== *Homepage disclaimer entry*

ifndef::backend-pdf[]
minmax::Homepage-disclaimer-entry[]
endif::[]
****
As a visitor of the Homepage
I should be able to see my disclaimer 
which gives an overview of the legal stuff
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Disclaimer view
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 636ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 262ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
DISCLAIMER.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 116ms)#
=====
And ::
=====
"disclaimerwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(374ms)#
=====
****

==== Scenario: Disclaimer view
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 562ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 755ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
DISCLAIMER.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 446ms)#
=====
And ::
=====
"disclaimerwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(340ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 263ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(017ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 170ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 685ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(031ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 440ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 927ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 499ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 436ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 604ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 379ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 793ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 193ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 432ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 797ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 536ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 254ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 647ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 274ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(009ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 312ms)#
=====
****

==== Scenario: Footer information
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 873ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 407ms)#
=====
****

==== Scenario: Amount of paragraphs
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 914ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(011ms)#
=====
Then ::
=====
"6" entries must be visible in the disclaimer icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 183ms)#
=====
****

[[Homepage-education-entry, Homepage education entry]]
=== *Homepage education entry*

ifndef::backend-pdf[]
minmax::Homepage-education-entry[]
endif::[]
****
As a visitor of the Homepage
I should be able to see my education 
which gives an overview of my education
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "education" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Education view
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 182ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(023ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 715ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(011ms)#
=====
Then ::
=====
EDUCATION.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 157ms)#
=====
And ::
=====
"educationwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(327ms)#
=====
****

==== Scenario: Education view
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 601ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(016ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 042ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(008ms)#
=====
Then ::
=====
EDUCATION.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 538ms)#
=====
And ::
=====
"educationwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(323ms)#
=====
****

==== Scenario: Basic education elements
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 561ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(017ms)#
=====
Then ::
=====
Ausbildung should be visible in the upper part icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 027ms)#
=====
****

==== Scenario: Basic education elements
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 303ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Education should be visible in the upper part icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 315ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 157ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 913ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 353ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 256ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 958ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 176ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 443ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 386ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 998ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 897ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 136ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(020ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 722ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 760ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(009ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 654ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 154ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(017ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 759ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 848ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 556ms)#
=====
****

==== Scenario: Footer information
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 300ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 737ms)#
=====
****

==== Scenario: Education is listed
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 144ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
FHDW must be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 478ms)#
=====
****

[[Homepage-main-entry, Homepage main entry]]
=== *Homepage main entry*

ifndef::backend-pdf[]
minmax::Homepage-main-entry[]
endif::[]
****
As a visitor of the Homepage
I should be able to see a welcome screen 
which gives a first impression
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: First View
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 701ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(009ms)#
=====
Then ::
=====
the title should equal "Maximilian Wollnik" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 082ms)#
=====
And ::
=====
Entwickler should be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(708ms)#
=====
****

==== Scenario: First View
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 185ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(008ms)#
=====
Then ::
=====
the title should equal "Maximilian Wollnik" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 579ms)#
=====
And ::
=====
Developer should be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(548ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 511ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 943ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 110ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 257ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 328ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(793ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 977ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(737ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 625ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(718ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 418ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(839ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 679ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(756ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 501ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(696ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 938ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(833ms)#
=====
****

==== Scenario: Footer information
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 576ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(978ms)#
=====
****

==== Scenario: Mobile Version
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 817ms)#
=====
Then ::
=====
the navigation should be changed into a toggle object icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 602ms)#
=====
****

==== Scenario: Unknown link
[small]#tags: @ALL,@HOME,@ignore#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 553ms)#
=====
When ::
=====
I navigate to "/a/b/c" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 447ms)#
=====
Then ::
=====
the title should equal "Maximilian Wollnik" icon:thumbs-up[role="green",title="Passed"] [small right]#(158ms)#
=====
****

[[Homepage-skill-entry, Homepage skill entry]]
=== *Homepage skill entry*

ifndef::backend-pdf[]
minmax::Homepage-skill-entry[]
endif::[]
****
As a visitor of the Homepage
I should be able to see my skills 
which gives a first impression
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "skill" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Work view
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 924ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 168ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
SKILL.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 837ms)#
=====
And ::
=====
"skillwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(430ms)#
=====
****

==== Scenario: Work view
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 934ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 419ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(013ms)#
=====
Then ::
=====
SKILL.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 124ms)#
=====
And ::
=====
"skillwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(191ms)#
=====
****

==== Scenario: Basic skill elements
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 728ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(007ms)#
=====
Then ::
=====
Angular should be visible in the carousel icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 293ms)#
=====
****

==== Scenario: Basic skill elements
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 706ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Angular should be visible in the carousel icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 863ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 126ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(014ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 006ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 994ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(009ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 551ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 241ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 225ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 251ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 548ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 789ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 371ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 565ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 461ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 643ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 881ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 047ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 608ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 550ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(014ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 032ms)#
=====
****

==== Scenario: Footer information
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 955ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(012ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 598ms)#
=====
****

==== Scenario: Samples is listed
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 733ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(009ms)#
=====
Then ::
=====
10 skills must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 011ms)#
=====
****

[[Homepage-social-block, Homepage social block]]
=== *Homepage social block*

ifndef::backend-pdf[]
minmax::Homepage-social-block[]
endif::[]
****
As a visitor of the Homepage
I should be able to see my socials 
which shows all plattforms
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "home" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Social block icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 396ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(021ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(022ms)#
=====
And ::
=====
I scroll to the bottom icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 068ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
Then ::
=====
Schreiben Sie mir eine Mail should be visible in the mail form icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I close the form again icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social block icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 933ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(008ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(004ms)#
=====
And ::
=====
I scroll to the bottom icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 001ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
Then ::
=====
Send me a mail should be visible in the mail form icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I close the form again icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Empty form
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 757ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(005ms)#
=====
When ::
=====
I scroll to the bottom icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 442ms)#
=====
And ::
=====
I click on the submit button icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
all form errors are shown icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 665ms)#
=====
And ::
=====
I close the form again icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
****

==== Scenario: Reset form icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 128ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
I scroll to the bottom icon:thumbs-up[role="green",title="Passed"] [small right]#(490ms)#
=====
Then ::
=====
all form errors are resetted after reopening icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 001ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I close the form again icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Wrong email icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(02s 732ms)#

IMPORTANT: StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=48.0.2564.82)
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 3.13.0-67-generic x86_64)
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at StaleElementReferenceError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-web...

=====
And ::
=====
I select "home" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the bottom icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I enter an invalid email address icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
only email error is shown icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
I close the form again icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 881ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 325ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 615ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 495ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 233ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 136ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 754ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 315ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 348ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 443ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 748ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 808ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 066ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 443ms)#
=====
****

[[Homepage-work-entry, Homepage work entry]]
=== *Homepage work entry*

ifndef::backend-pdf[]
minmax::Homepage-work-entry[]
endif::[]
****
As a visitor of the Homepage
I should be able to see my work 
which gives an impression of some samples
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "work" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Work view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 574ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(010ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 003ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
WORK.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"workwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Work view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 001ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
WORK.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"workwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Basic work elements icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 009ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Muster should be visible in the upper part icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Basic work elements icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 004ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Samples should be visible in the upper part icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 761ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 002ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 010ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(04s 913ms)#

IMPORTANT: StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=48.0.2564.82)
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 3.13.0-67-generic x86_64)
    at WebDriverError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-webdriver/error.js:27:10)
    at StaleElementReferenceError (/var/jenkins_home/sharedspace/node_modules/protractor/node_modules/selenium-web...

=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 215ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(010ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 003ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 006ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 008ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "work" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 800ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 573ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 141ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 963ms)#
=====
****

==== Scenario: Footer information icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 135ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-down[role="red",title="Failed"] [small right]#(05s)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
****

==== Scenario: Samples is listed
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 612ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
2 samples must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 817ms)#
=====
****


Copyright 2016 Maximilian Wollnik