:toc: right
:backend: html5
:doctitle: Homepage
:doctype: book
:icons: font
:!numbered:
:!linkcss:
:sectanchors:
:sectlink:
:docinfo:
:toclevels: 2

= Homepage
All source files for my private homepage

== *Version*
=== 1.15.0 - 03/08/2017

==== NEW
    ---------------------
    chg: cv-update
    - adding latest projects
    - removing eureka


==== CHANGE
    ---------------------
    cv-update
    - adding latest projects
    - removing eureka


==== FIX
    ---------------------
    chg: cv-update
    - adding latest projects
    - removing eureka


=== 1.14.0 - 14/09/2016

==== NEW
    ---------------------
    updated CV
    - added Diebold Nixdorf


=== 1.12.0 - 11/03/2016

==== NEW
    ---------------------
    http-status "not found" causes a redirect
    - if an invalid url is executed the user is redirected to the main page


==== CHANGE
    ---------------------
    finalizing new readme
    - including cukedoctor into the final readme-file
    
    ---------------------
    changing format from md to adoc
    - preparing to use cukedoctor for cucumber report
    
    ---------------------
    added cucumber testcases for 404
    - testing unknown links
    
    ---------------------
    using cucumber for e2e tests
    - e2e tests changed to work with cucumber and features
    
    ---------------------
    changes.xml not needed anymore
    - changelog is handled via the commit messages
    
    ---------------------
    restructured
    - moving all source files to src


==== FIX
    ---------------------
    redirecting 404 back to main entry
    - adding own 404.html which redirects to /
    
    ---------------------
    corrected bower folder
    - need to ignore a certain string
    - basePath is used to find components
    
    ---------------------
    resetting mail form
    - form was not resetted when the "x" button was pressed


=== 1.12.0 - 23/02/2016

==== NEW
    ---------------------
    added robots.txt
    - for allowing search engines to check my homepage
    - currently i don't have anything to hide
    
    ---------------------
    pdf profile
    - added link to download
    
    ---------------------
    added files to create a pdf profile
    - using asciidoctor-pdf to create pdf


==== CHANGE
    ---------------------
    new pdf profile layout
    - adding different table style
    - completed skill list
    
    ---------------------
    removing profile from version
    - the new version name contains the profile now
    
    ---------------------
    creating new build process with jenkins
    - using nexus for all artifacts
    
    ---------------------
    moving conf-files to elk repository
    - don't provide conf-file per build
    
    ---------------------
    added background
    - previously the image had a transparent layer
    - added a grey background for pdf profile
    
    ---------------------
    remove unneeded image
    - only using own background image


=== 1.11.0 - 08/02/2016

==== CHANGE
    ---------------------
    updated elk stack
    - using json output for elk
    
    ---------------------
    using json as logging output
    - with json it should be easier to use ELK


=== 1.10.0 - 02/02/2016

==== CHANGE
    ---------------------
    building node modules from maven
    - as all jenkins problems could be solved, the whole build is done via maven
    
    ---------------------
    changed favicon
    - using background image as new favicon
    - previous one was not recognizable


=== 1.9.0 - 01/02/2016

==== NEW
    ---------------------
    speeding up docker build
    - adding .dockerignore to send only important files to docker engine
    
    ---------------------
    add test for back browsing
    - added a test to check if back browsing works
    - previously back navigation refreshed the same page


==== CHANGE
    ---------------------
    updated spring cloud
    - trying to use latest clout starter pom angel.sr6
    - jenkins still makes problems although mvn works on a commandline
    
    ---------------------
    providing more information about my cv
    - added a detailed description of my life so far


==== FIX
    ---------------------
    new: speeding up docker build
    - adding .dockerignore to send only important files to docker engine


=== 1.8.0 - 15/01/2016

==== CHANGE
    ---------------------
    corrected jenkins jobs
    - increased memory on jenkins server
    - aligned mvn directories on master and slave

=== 1.7.0 - 15/01/2016

==== NEW
    ---------------------
    enabled firefox tests
    - e2e tests executed with firefox
    - currently the bootstrap mail modal does not open with protractor
    - but the mail modal works when used manually

=== 1.6.0 - 13/01/2016

==== NEW
    ---------------------
    templates for readme
    - added initial changelog
    - added templates to create final readme file
    
    ---------------------
    commit template
    - start of new changelog file
    - everything is driven via the commit messages


==== CHANGE
    ---------------------
    increase timer for e2e test
    - sometimes selenium test cases fail, after a navigation is made
    - added additional timer to wait before the whole page is loaded


==== FIX
    ---------------------
    back button did not work
    - because of a wrong anchor, any back button refreshed the page
    - added a div with the id 'content' on the home page to fix that
    - adapted test cases


=== 1.5.0 - 06/01/2016

=== 1.4.0 - 06/01/2016

=== 1.3.0 - 25/12/2015

=== 1.2.0 - 09/11/2015

=== 1.1.0 - 31/10/2015

=== 1.0.0 - 18/10/2015

=== 0.4.0 - 13/10/2015

=== 0.3.0 - 26/09/2015

=== 0.2.0 - 24/09/2015

=== 0.1.0 - 11/09/2015

= *Living Documentation*

== *Summary*
[cols="12*^m", options="header,footer"]
|===
3+|Scenarios 7+|Steps 2+|Features: 7

|[green]#*Passed*#
|[red]#*Failed*#
|Total
|[green]#*Passed*#
|[red]#*Failed*#
|[purple]#*Skipped*#
|[maroon]#*Pending*#
|[yellow]#*Undefined*#
|[blue]#*Missing*#
|Total
|Duration
|Status

12+^|*<<Homepage-cv-entry>>*
|14
|3
|17
|53
|2
|5
|0
|0
|2
|62
|01m 26s 686ms
|[red]#*failed*#

12+^|*<<Homepage-disclaimer-entry>>*
|13
|1
|14
|47
|0
|0
|0
|0
|2
|49
|52s 710ms
|[red]#*failed*#

12+^|*<<Homepage-education-entry>>*
|15
|1
|16
|55
|0
|0
|0
|0
|2
|57
|01m 02s 705ms
|[red]#*failed*#

12+^|*<<Homepage-main-entry>>*
|14
|1
|15
|35
|0
|0
|0
|0
|1
|36
|54s 558ms
|[red]#*failed*#

12+^|*<<Homepage-skill-entry>>*
|15
|1
|16
|55
|0
|0
|0
|0
|2
|57
|01m 07s 360ms
|[red]#*failed*#

12+^|*<<Homepage-social-block>>*
|12
|1
|13
|54
|0
|0
|0
|0
|2
|56
|48s 833ms
|[red]#*failed*#

12+^|*<<Homepage-work-entry>>*
|14
|2
|16
|54
|1
|0
|0
|0
|2
|57
|01m 31s 748ms
|[red]#*failed*#
12+^|*Totals*
|97|10|107|353|3|5|0|0|13|374 2+|07m 44s 603ms
|===

== *Features*

[[Homepage-cv-entry, Homepage cv entry]]
=== *Homepage cv entry*

minmax::Homepage-cv-entry[]
****
As a visitor of the Homepage
I should be able to see my cv 
which gives an overview of my life
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "cv" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: CV view icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 007ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
And ::
=====
I select "cv" icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
Then ::
=====
CV.HEADLINE.PRE should NOT be visible icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
And ::
=====
"cvwrap" must be in the display area icon:thumbs-down[role="purple",title="Skipped"] [small right]#(000ms)#
=====
****

==== Scenario: CV view
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 406ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(009ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 241ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
CV.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 625ms)#
=====
And ::
=====
"cvwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(098ms)#
=====
****

==== Scenario: Timeline content
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 228ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(005ms)#
=====
Then ::
=====
Das habe should be visible in the timeline icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 724ms)#
=====
****

==== Scenario: Timeline content
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 393ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
That is should be visible in the timeline icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 214ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 110ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 736ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 369ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 969ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 957ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(024ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 359ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 441ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(004ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 138ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 067ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 767ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 321ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 161ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 438ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 342ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 534ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 532ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 702ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 510ms)#
=====
****

==== Scenario: Footer information
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 230ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 951ms)#
=====
****

==== Scenario: Amount of experiences icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 704ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
"15" entries must be visible in the timeline icon:thumbs-down[role="red",title="Failed"] [small right]#(01s 670ms)#

IMPORTANT: AssertionError: expected 17 to equal 15
=====
****

==== Scenario: Back navigation
[small]#tags: @ALL,@CV#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 906ms)#
=====
And ::
=====
I select "cv" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
When ::
=====
I click on the back button icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Das habe should be visible in the timeline icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 745ms)#
=====
****

[[Homepage-disclaimer-entry, Homepage disclaimer entry]]
=== *Homepage disclaimer entry*

minmax::Homepage-disclaimer-entry[]
****
As a visitor of the Homepage
I should be able to see my disclaimer 
which gives an overview of the legal stuff
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "disclaimer" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Disclaimer view
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 419ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 066ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
DISCLAIMER.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 893ms)#
=====
And ::
=====
"disclaimerwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(091ms)#
=====
****

==== Scenario: Disclaimer view
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 629ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(007ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 087ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
DISCLAIMER.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 652ms)#
=====
And ::
=====
"disclaimerwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(122ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 929ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 357ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 015ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(003ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 623ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 202ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 463ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 725ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 149ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 315ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 415ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 268ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 347ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 181ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 073ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 571ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 484ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 132ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 306ms)#
=====
****

==== Scenario: Footer information
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 731ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 249ms)#
=====
****

==== Scenario: Amount of paragraphs
[small]#tags: @ALL,@DISCLAIMER#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 503ms)#
=====
And ::
=====
I select "disclaimer" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
"6" entries must be visible in the disclaimer icon:thumbs-up[role="green",title="Passed"] [small right]#(660ms)#
=====
****

[[Homepage-education-entry, Homepage education entry]]
=== *Homepage education entry*

minmax::Homepage-education-entry[]
****
As a visitor of the Homepage
I should be able to see my education 
which gives an overview of my education
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "education" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Education view
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 320ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(869ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
EDUCATION.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 583ms)#
=====
And ::
=====
"educationwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(078ms)#
=====
****

==== Scenario: Education view
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 438ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(451ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(004ms)#
=====
Then ::
=====
EDUCATION.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 443ms)#
=====
And ::
=====
"educationwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(082ms)#
=====
****

==== Scenario: Basic education elements
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 658ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(005ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Ausbildung should be visible in the upper part icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 193ms)#
=====
****

==== Scenario: Basic education elements
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 539ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(009ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
Education should be visible in the upper part icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 575ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 912ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(003ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 965ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 754ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(003ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 912ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 495ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 060ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 001ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(008ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 525ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 715ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 108ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 395ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(994ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 181ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 084ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 332ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 175ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 306ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 325ms)#
=====
****

==== Scenario: Footer information
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 966ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 113ms)#
=====
****

==== Scenario: Education is listed
[small]#tags: @ALL,@EDUCATION#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 075ms)#
=====
And ::
=====
I select "education" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
FHDW must be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 002ms)#
=====
****

[[Homepage-main-entry, Homepage main entry]]
=== *Homepage main entry*

minmax::Homepage-main-entry[]
****
As a visitor of the Homepage
I should be able to see a welcome screen 
which gives a first impression
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: First View
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 099ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
the title should equal "Maximilian Wollnik" icon:thumbs-up[role="green",title="Passed"] [small right]#(818ms)#
=====
And ::
=====
Entwickler should be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(329ms)#
=====
****

==== Scenario: First View
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 303ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(003ms)#
=====
Then ::
=====
the title should equal "Maximilian Wollnik" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 002ms)#
=====
And ::
=====
Developer should be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(386ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 545ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 844ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 572ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(005ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 339ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 126ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(610ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 331ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(561ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 964ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(639ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 965ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(606ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 960ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(578ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 532ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(784ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 835ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(633ms)#
=====
****

==== Scenario: Footer information
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 367ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(647ms)#
=====
****

==== Scenario: Mobile Version
[small]#tags: @ALL,@HOME#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 489ms)#
=====
Then ::
=====
the navigation should be changed into a toggle object icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 537ms)#
=====
****

==== Scenario: Unknown link
[small]#tags: @ALL,@HOME,@ignore#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 972ms)#
=====
When ::
=====
I navigate to "/a/b/c" icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 114ms)#
=====
Then ::
=====
the title should equal "Maximilian Wollnik" icon:thumbs-up[role="green",title="Passed"] [small right]#(042ms)#
=====
****

[[Homepage-skill-entry, Homepage skill entry]]
=== *Homepage skill entry*

minmax::Homepage-skill-entry[]
****
As a visitor of the Homepage
I should be able to see my skills 
which gives a first impression
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "skill" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Work view
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 476ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(004ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 473ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(010ms)#
=====
Then ::
=====
SKILL.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 739ms)#
=====
And ::
=====
"skillwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(324ms)#
=====
****

==== Scenario: Work view
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 280ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 138ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
SKILL.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 121ms)#
=====
And ::
=====
"skillwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(069ms)#
=====
****

==== Scenario: Basic skill elements
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 170ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(005ms)#
=====
Then ::
=====
Angular should be visible in the carousel icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 970ms)#
=====
****

==== Scenario: Basic skill elements
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 814ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(009ms)#
=====
Then ::
=====
Angular should be visible in the carousel icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 374ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 195ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 062ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 102ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 841ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 077ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 694ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 811ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 437ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 166ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 367ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 375ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(003ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 209ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 141ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 434ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 098ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 192ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 858ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 115ms)#
=====
****

==== Scenario: Footer information
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 540ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 316ms)#
=====
****

==== Scenario: Samples is listed
[small]#tags: @ALL,@SKILL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 661ms)#
=====
And ::
=====
I select "skill" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
10 skills must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(645ms)#
=====
****

[[Homepage-social-block, Homepage social block]]
=== *Homepage social block*

minmax::Homepage-social-block[]
****
As a visitor of the Homepage
I should be able to see my socials 
which shows all plattforms
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "home" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Social block
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 981ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
And ::
=====
I scroll to the bottom icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 053ms)#
=====
Then ::
=====
Schreiben Sie mir eine Mail should be visible in the mail form icon:thumbs-up[role="green",title="Passed"] [small right]#(135ms)#
=====
And ::
=====
I close the form again icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
****

==== Scenario: Social block
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 277ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
And ::
=====
I scroll to the bottom icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 171ms)#
=====
Then ::
=====
Send me a mail should be visible in the mail form icon:thumbs-up[role="green",title="Passed"] [small right]#(092ms)#
=====
And ::
=====
I close the form again icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
****

==== Scenario: Empty form
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 305ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
I scroll to the bottom icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 265ms)#
=====
And ::
=====
I click on the submit button icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
all form errors are shown icon:thumbs-up[role="green",title="Passed"] [small right]#(971ms)#
=====
And ::
=====
I close the form again icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
****

==== Scenario: Reset form
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 220ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
I scroll to the bottom icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
all form errors are resetted after reopening icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 537ms)#
=====
And ::
=====
I close the form again icon:thumbs-up[role="green",title="Passed"] [small right]#(012ms)#
=====
****

==== Scenario: Wrong email
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 162ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
When ::
=====
I scroll to the bottom icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
And ::
=====
I click on the envelope icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 715ms)#
=====
And ::
=====
I enter an invalid email address icon:thumbs-up[role="green",title="Passed"] [small right]#(003ms)#
=====
Then ::
=====
only email error is shown icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 478ms)#
=====
And ::
=====
I close the form again icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 327ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(952ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 902ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(919ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 805ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 056ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 874ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 154ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 111ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 006ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 625ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(880ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@SOCIAL#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 833ms)#
=====
And ::
=====
I select "home" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(963ms)#
=====
****

[[Homepage-work-entry, Homepage work entry]]
=== *Homepage work entry*

minmax::Homepage-work-entry[]
****
As a visitor of the Homepage
I should be able to see my work 
which gives an impression of some samples
****

==== Background icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-down[role="blue",title="Missing"]
=====
And ::
=====
I select "work" icon:thumbs-down[role="blue",title="Missing"]
=====
****

==== Scenario: Work view
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 782ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(660ms)#
=====
And ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
WORK.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 479ms)#
=====
And ::
=====
"workwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(061ms)#
=====
****

==== Scenario: Work view
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 826ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
I scroll to the top icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 971ms)#
=====
And ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(003ms)#
=====
Then ::
=====
WORK.HEADLINE.PRE should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 914ms)#
=====
And ::
=====
"workwrap" must be in the display area icon:thumbs-up[role="green",title="Passed"] [small right]#(064ms)#
=====
****

==== Scenario: Basic work elements
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 107ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(005ms)#
=====
Then ::
=====
Muster should be visible in the upper part icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 938ms)#
=====
****

==== Scenario: Basic work elements
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 669ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(006ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(003ms)#
=====
Then ::
=====
Samples should be visible in the upper part icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 035ms)#
=====
****

==== Scenario: Dummy text removed
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 810ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the de flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(002ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 390ms)#
=====
****

==== Scenario: Dummy text removed icon:thumbs-down[role="red",title="Failed"]
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 971ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
When ::
=====
the en flag is clicked icon:thumbs-up[role="green",title="Passed"] [small right]#(000ms)#
=====
Then ::
=====
Lorem Ipsum should NOT be visible icon:thumbs-down[role="red",title="Failed"] [small right]#(05s 001ms)#

IMPORTANT: Error: Step timed out after 5000 milliseconds
    at Timer.listOnTimeout (timers.js:92:15)
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 725ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to xing should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 859ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 708ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to facebook should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 202ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 816ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to github should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 838ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 842ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to stack-overflow should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 861ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 641ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to google-plus should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 006ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 133ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to linkedin should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 330ms)#
=====
****

==== Scenario: Social linking
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 824ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a link to envelope-square should be available icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 336ms)#
=====
****

==== Scenario: Footer information
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(02s 608ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
a footer must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(04s 454ms)#
=====
****

==== Scenario: Samples is listed
[small]#tags: @ALL,@WORK#


****
Given ::
=====
I navigate to "/" icon:thumbs-up[role="green",title="Passed"] [small right]#(01s 806ms)#
=====
And ::
=====
I select "work" icon:thumbs-up[role="green",title="Passed"] [small right]#(001ms)#
=====
Then ::
=====
2 samples must be available icon:thumbs-up[role="green",title="Passed"] [small right]#(03s 022ms)#
=====
****


Copyright 2016 Maximilian Wollnik
